### ISSUE TITLE
[Menu]: clicking options on mobile also triggers events of elements below

### ISSUE THREAD

**Issue by fluoxe7ine** [chakra-ui/zag#776] opened 2023-08-01 11:28 UTC
# 🐛 Bug report

When I have a context menu over some element with event handlers, clicking on menu option also triggers events of underlying element. It only reproduces on touch devices, on desktop everything works fine. Probably related to #756 

## 💥 Steps to reproduce

1. Go to https://2jwv52.csb.app/
2. Enter the mobile/responsive dev mode (or make sure you have touch mode enabled)
3. Open context menu via press&hold
4. Select an option which is located over pink section
5. Notice how counter is increased

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/zag-js-menu-2jwv52?file=/src/index.js

## 🧐 Expected behavior

Clicks of underlying element is not triggered (the same as on desktop)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |     0.13       |
| Browser          |     All       |
| Operating System |      macOS 13.1      |

## 📝 Additional information

I've debug a little in `examples/next-ts/pages/context-menu.tsx`. I've created almost the same markup as in the sandbox and log events from `menu.connect.ts`. It looks like the difference between desktop and mobile is that mobile doesn't trigger `onClick` event when desktop does.

Events when testing on mobile:
![Screenshot 2023-08-01 at 14 18 37](https://github.com/chakra-ui/zag/assets/31725157/cf31b31b-05cc-4419-94d7-8d87342f43ca)

Events when testing on desktop:
![Screenshot 2023-08-01 at 14 18 57](https://github.com/chakra-ui/zag/assets/31725157/10dff3de-a4e8-43d9-9fb8-538320b992c5)

Looks like "onPointerUp" event executes much faster than "onClick" so zag closes root menu even before handling "onClick" on list item, so click event somehow passes to underlying element. Should be noticed, that if disable "closeOnSelect" or comment "onPointerUp" handler, everything works fine, both desktop and mobile have same events.

**Comment by segunadebayo** [comment] 2023-08-02 00:55
Duplicate of #756 

I think the underlying root cause is the same. We’ll get to the bottom of it shortly

**Closed by segunadebayo** 2023-08-02 00:55 UTC
