### ISSUE TITLE
[Pressable] Discrepancy in keyboard handling between enter and spacebar

### ISSUE THREAD

**Issue by pawelblaszczyk5** [chakra-ui/zag#653] opened 2023-05-17 14:22 UTC
# 🐛 Bug report

When the element created with the Pressable Machine is clicked via keyboard there is a difference between "enter" and "spacebar" key. If you hold down the key both of them transition the machine into "pressed" state. After releasing though, presses with "spacebar" invokes the "onPress" handler and presses with "enter" don't.

## 💥 Steps to reproduce

1. Go to the reproduction linked below
2. Focus the button with keyboard
3. Press spacebar
4. Press enter
5. The presses count is 1

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/determined-davinci-f0eh07?file=/App.tsx

## 🧐 Expected behavior

I'd expect that both Enter and Spacebar triggers presses, same as with standard button element.

## 🧭 Possible Solution

I've tried to stumble through the code of the machine, but I've couldn't grasp it, so nothing unfortunately 😞 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |    0.9.1        |
| Browser          |    Arc - Chromium under the hood - 113.0.5672.92        |
| Operating System |       macOS Version 13.3.1     |

## 📝 Additional information

Btw. should I use the button created with Pressable machine as a trigger for stuff like Popover or Menu (with manual wrapping onClick->onPress) or is it unnecessary, harmful?

**Comment by segunadebayo** [comment] 2023-05-18 19:24
Hi @pawelblaszczyk5,

Thanks for reporting this. I appreciate you trying to get to the root cause of the issue.

I've gone ahead to push the fix for this. It should be released pretty soon.

Regarding your question, it's really up to you to decide whether to use pressable within your component. Ideally, you could wrap pressable in a button and map `onClick` from other machines to the `onPress` of your button.

**Closed by segunadebayo** 2023-05-18 19:24 UTC

**Comment by pawelblaszczyk5** [comment] 2023-05-19 10:37
Thanks a lot for fixing it! I've played a bit with composing Pressable with other machines and it looks like it's not really possible currently. Because `onPress` event doesn't provide native event, which other machines expect to do stuff like currentTarget/preventDefault etc.
