### ISSUE TITLE
Error `Could not resolve "react"` in Vue Project

### ISSUE THREAD

**Issue by visualjerk** [chakra-ui/zag#511] opened 2023-02-06 18:09 UTC
# 🐛 Bug report

Using `zag-js/vue` in a vite project and running `npm run dev` results in the following error:

```
✘ [ERROR] Could not resolve "react"

    node_modules/use-sync-external-store/cjs/use-sync-external-store-shim.development.js:26:30:
      26 │           var React = require('react');
         ╵                               ~~~~~~~

  You can mark the path "react" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
```

## 💥 Steps to reproduce

1. Create a fresh Vue project with `npm create vite@latest`
2. Install `zag-js/vue`
3. Import it in `App.vue`

## 💻 Link to reproduction

[CodeSandbox reproduction: https://your-codesandbox-link-goes-here.io](https://stackblitz.com/edit/vitejs-vite-qrpepr?file=package.json,src%2FApp.vue)

## 🧐 Expected behavior

`npm run dev` runs without errors

## 🧭 Possible Solution

This seems to stem from an update in `valtio`: https://github.com/pmndrs/valtio/issues/591

A possible solution is described here: https://github.com/pmndrs/valtio/issues/591#issuecomment-1319478205

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | @zag-js/vue: 0.2.8 |
| Browser          |  -          |
| Operating System | -           |

**Comment by anubra266** [comment] 2023-02-06 20:12
Closing as duplicate of #509 which is now fixed. Please upgrade and try again.

**Closed by anubra266** 2023-02-06 20:12 UTC
