### ISSUE TITLE
`TreeView` loses focus under some conditions

### ISSUE THREAD

**Issue by mr04vv** [chakra-ui/zag#1874] opened 2024-09-16 14:07 UTC
### Description

The following is when operating with Keyboard only.
If you open a parent node, select a child node, and then close the parent node and then focus on a non-TreeView, you will not be able to focus on the TreeView.

### Link to Reproduction (or Detailed Explanation)

https://ark-ui.com/react/docs/components/tree-view

### Steps to Reproduce

1. Go to https://ark-ui.com/react/docs/components/tree-view
2. Press the `Tab` key to focus on `item 1`
3. Press the `Right Arrow` key to open `item 1`
4. Press the `Right Arrow` key to focus on `item 1.1`
5. Press the `Enter` key to select `item 1.1`
6. Press the `Left Arrow` key to focus on `item 1`
7. Press the `Left Arrow` key to close `item 1`
8. Press the `Tab` key to focus on next element(Not treeview)
9. Press the `Shift + Tab` key to focus on `TreeView`

TreeView does not get focus after 9 operations.

https://github.com/user-attachments/assets/96fb4dc4-d5a4-46cd-9cf7-4ee584138337

### Ark UI Version

3.12.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by segunadebayo** [comment] 2024-10-26 15:06
Duplicate of #1751. Will work on a fix for this shortly

**Closed by segunadebayo** 2024-10-26 15:06 UTC
